[workspace]
resolver = "3"
members = ["boa-server", "boa-www", "library/boa-core"]

[workspace.dependencies]
boa-core = { path = "./library/boa-core/" }

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
unwrap_used = "deny"
