[package]
name = "boa-server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.7"
boa-core = { workspace = true }
tokio = { version = "1.48.0", features = ["full"] }

[lints]
workspace = true
